create table "public"."migration" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" text not null default ''::text,
    "status" text not null default ''::text,
    "ownerID" uuid not null default auth.uid()
);


alter table "public"."migration" enable row level security;

CREATE UNIQUE INDEX migration_pkey ON public.migration USING btree (id);

alter table "public"."migration" add constraint "migration_pkey" PRIMARY KEY using index "migration_pkey";

alter table "public"."migration" add constraint "migration_ownerID_fkey" FOREIGN KEY ("ownerID") REFERENCES auth.users(id) ON UPDATE CASCADE not valid;

alter table "public"."migration" validate constraint "migration_ownerID_fkey";

grant delete on table "public"."migration" to "anon";

grant insert on table "public"."migration" to "anon";

grant references on table "public"."migration" to "anon";

grant select on table "public"."migration" to "anon";

grant trigger on table "public"."migration" to "anon";

grant truncate on table "public"."migration" to "anon";

grant update on table "public"."migration" to "anon";

grant delete on table "public"."migration" to "authenticated";

grant insert on table "public"."migration" to "authenticated";

grant references on table "public"."migration" to "authenticated";

grant select on table "public"."migration" to "authenticated";

grant trigger on table "public"."migration" to "authenticated";

grant truncate on table "public"."migration" to "authenticated";

grant update on table "public"."migration" to "authenticated";

grant delete on table "public"."migration" to "service_role";

grant insert on table "public"."migration" to "service_role";

grant references on table "public"."migration" to "service_role";

grant select on table "public"."migration" to "service_role";

grant trigger on table "public"."migration" to "service_role";

grant truncate on table "public"."migration" to "service_role";

grant update on table "public"."migration" to "service_role";


